language: python
env:
  - BACKEND_DIR='backend'
python:     # current default Python on Travis CI
 
  - "3.8"
  
addons:
  sonarcloud:
    organization: "Jijogeorge69-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

# command to install dependencies
install:
  - pip install -r $BACKEND_DIR/requirements.txt
  
# command to run tests
script:
  - pytest --setup-show $BACKEND_DIR/tests/functional

after_script:
  - codecov
