language: python
env:
  - BACKEND_DIR='backend' FRONTEND_DIR='frontend'
python:     # current default Python on Travis CI
 
  - "3.8"
  
addons:
  sonarcloud:
    organization: "jijogeorge69" # the key of the org you chose at step #3
    token:
      secure: "nsslG8PGj15/MbNaDIksghS7CCVTYGdcZy+D472xqIEnWkIyYaei6Zq7V8JBBsylw/K+/IGNIIdxJZCj266EwwqewDadcnbC+TF4ujDOJN7AbPsAHPXbvjG+MaHjfo136z6A48HQ8Dr8lvIY5Smvt3IeeR/WfoBN7xI7yg6H1x8zWuSnV0m1ov8pAiPBub0WWCDEtopKwgpZxJmM6yDE5fdzNstN/NxKX4yAY0T/+zoOzd5AaA7GVpbz/y4Y0pMncVspJkErg3m79CcCQtaG6H+xyayzuVTE1Egk2KromAofw6VWz7GzY/4m7elhI9BV/wWmcnY+Ha/mT2H8cIuEi6EPIZVPuoms7Sat4N62LNe7GgGjz1+D/zmWuzh8XEe9JCm+lLNC4zv4zXwH3UcVql1Uez8K0ug7bE+Q6ex/tUDxwAcYN9aG2NupmXCUPdmKICPZ0LxJLwd5eZiWgNeP+DfyZLvKya0siqd0h0V42qMMuqYvYT9kFPIWoffysu0RJorUTj+MacU8X5HyHpK7sEgsAGtKeOFeBwCoiJ19b9I0NdI2WmN9uunY4HA58HviZX4wrOQsf0pwllT24PCDQPq5iryDIEHe94kjP2V9Lb1/U4L6jZkYf8q1WHq8eJRail+C4ZJPK0nPPz1Ru3OvlbOs0yiKi7zqZPEMd1GYR3A="
# command to install dependencies
install:
  - pip install -r $BACKEND_DIR/requirements.txt
  - npm --prefix $FRONTEND_DIR install
  
  
# command to run tests
script:
  - coverage run -m pytest --setup-show $BACKEND_DIR/tests/functional
  - npm --prefix $FRONTEND_DIR test
  - sonar-scanner

after_script:

 
