language: python
env:
  - BACKEND_DIR='backend' FRONTEND_DIR='frontend'
python:     # current default Python on Travis CI

  - "3.8"

addons:
  sonarcloud:
    organization: "jijogeorge69" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
# command to install dependencies
install:
  - pip install -r $BACKEND_DIR/requirements.txt
  - npm --prefix $FRONTEND_DIR install
  - pip install codecov
  - pip install pylint



# command to run tests
script:
  - pytest --setup-show $BACKEND_DIR/tests/functional
  - coverage run -m pytest $BACKEND_DIR/tests/functional
  - npm --prefix $FRONTEND_DIR test
  - pylint $BACKEND_DIR/project/**/**.py
  # - pylint $BACKEND_DIR/tests/functional/**
  #- sonar-scanner

after_script:
  - codecov
