language: python
python:     # current default Python on Travis CI
 
  - "3.8"
  
addons:
  sonarcloud:
    organization: "Jijogeorge69-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --setup-show tests/functional
  - coverage run -m pytest --setup-show tests/functional
  - coverage report -m
  - coverage xml
  - coverage html

after_script:
  - codecov
